### ISSUE TITLE
Can't find Proxy IDs

### ISSUE THREAD

**Issue by lawtancool** [itsfrosty/control4-2way-web-driver#1]
I have successfully inserted the driver into the C4 project, but when I hover over my devices all I get is a model number. How do I find the proxy ids?

**Comment by lorddaren** [comment]
I might be a little late for you reply, but I think this has something to do with the version of Control4 that you are running. If you are 2.5.3 you are probably not going to find them. I am not sure what version they added them but if I was to venture a guess I bet it would be 2.6. I am running on 2.9.1 and I have them available.
